# Grammar {#gram}

## Reference Books:

+ **Modern English a Practical Reference Guide:** This book gives a breakdown of parts of speech as well as phrasal, clasal and sentence level discourse explanations. Frank, M. (1993). Modern English: A Practical Reference Guide (2nd ed.). Regents/Prentice Hall.

+ **A Concise Grammar of Contemporary English:** This book is another oldie but goodie. Got a student that constantly stumps you with very detailed questions? You are likely to find the answer within these hardback book covers. You may have to reword it a little to get students to understand, but it will save you hours of Google searches for obscure grammatical details. Quirk, R., Director Survey of English Usage Sidney Greenbaum, & Greenbaum, S. (1973). A Concise Grammar of Contemporary English. Harcourt Brace Jovanovich.

+ **English Grammar for Students of Spanish:** This book written in English will help you teach L1 English speakers an L2 Spanish. However, by looking at the items that these English speaking students may run into while learning Spanish can help you understand where and why your L1 Spanish students are encountering errors in the learning of English. If you can read in Spanish I recommend this book paired with the next one in our list _Gramática española para estudiantes de inglés_. Spinelli, E. (2012). English Grammar for Students of Spanish: The Study Guide for Those Learning Spanish (J. Morton (ed.); 7th ed.). The Olivia and Hill Press.

+ **Gramática española para estudiantes de inglés:** This book is written in Spanish so it will be helpful to be able to read it in Spanish or have someone who is willing to work through it with you. You can also pair it with the previous item on our list _English Grammar for Students of Spanish_ for a better understanding of the difference between English and Spanish. Please note that this is not a direct translation as L1-L2 language pairings do not struggle with all the same points of difference between the two languages even though there is usually some overlap. Levenson, A. I., & Eggly, S. (1993). Gramática española para estudiantes de inglés (J. Morton (ed.)). The Olivia and Hill Press.